//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE_U1_W3_D5_Progetto_ECommerce {
    
    
    public partial class ViewSwitcher {
    }
}
